/** Authentication variables */
const SIGNUP = "SIGN_UP";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";

export { SIGNUP, LOGIN, LOGOUT };

/** Like video variables */
const UPDATE_LIKED_VIDEOS = "UPDATE_LIKED_VIDEOS";
const CLEAR_LIKED_VIDEOS = "CLEAR_LIKED_VIDEOS";

export { UPDATE_LIKED_VIDEOS, CLEAR_LIKED_VIDEOS };

/** Watch later variables */
const UPDATE_WATCH_LATER_VIDEOS = "UPDATE_WATCH_LATER_VIDEOS";
const CLEAR_WATCH_LATER_VIDEOS = "CLEAR_WATCH_LATER_VIDEOS";

export { UPDATE_WATCH_LATER_VIDEOS, CLEAR_WATCH_LATER_VIDEOS };
