/** Authentication variables */
const SIGNUP = "SIGN_UP";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";

export { SIGNUP, LOGIN, LOGOUT };

/** Like video variables */
const UPDATE_LIKED_VIDEOS = "UPDATE_LIKED_VIDEOS";
const CLEAR_LIKED_VIDEOS = "CLEAR_LIKED_VIDEOS";

export { UPDATE_LIKED_VIDEOS, CLEAR_LIKED_VIDEOS };

/** Watch later variables */
const UPDATE_WATCH_LATER_VIDEOS = "UPDATE_WATCH_LATER_VIDEOS";
const CLEAR_WATCH_LATER_VIDEOS = "CLEAR_WATCH_LATER_VIDEOS";

export { UPDATE_WATCH_LATER_VIDEOS, CLEAR_WATCH_LATER_VIDEOS };

/** History variables */
const UPDATE_HISTORY = "UPDATE_HISTORY";
const CLEAR_HISTORY = "CLEAR_HISTORY";

export { UPDATE_HISTORY, CLEAR_HISTORY };

/** Playlist variables */
const UPDATE_PLAYLISTS = "UPDATE_PLAYLISTS";
const ADD_TO_PLAYLISTS = "ADD_TO_PLAYLISTS";

export { UPDATE_PLAYLISTS, ADD_TO_PLAYLISTS };
